### ISSUE TITLE
怎么可以联系到你，我看你给pitaya改了很多内容

### ISSUE THREAD

**Issue by supermigo** [alkaid/goerrors#1]
怎么可以联系到你，我看你给pitaya改了很多内容

**Comment by alkaid** [comment]
> 怎么可以联系到你，我看你给pitaya改了很多内容

有什么事吗同学

**Comment by supermigo** [comment]
你对pitaya的改造基本堪称完美啊。 很多bug 基本都修了，这个要怎么合并更新pitaya之前的代码？

**Comment by alkaid** [comment]
> 你对pitaya的改造基本堪称完美啊。 很多bug 基本都修了，这个要怎么合并更新pitaya之前的代码？

已经合并到最新
